# Generated by Django 4.0 on 2022-04-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genarator',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
