# Generated by Django 4.0 on 2022-05-03 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buen', '0002_genarator_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='genarator',
            name='stock',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Soled', 'Soled')], default='Inactive', max_length=400),
        ),
    ]
