# Generated by Django 3.2.13 on 2022-05-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buen', '0005_remove_soledserial_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soledserial',
            name='date_sold',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='soledserial',
            name='time_sold',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
