# Generated by Django 3.2.13 on 2022-05-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buen', '0006_auto_20220519_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='soledserial',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
