# Generated by Django 3.2.13 on 2022-05-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buen', '0007_soledserial_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genarator',
            name='stock',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Sold', 'Sold')], default='Inactive', max_length=400),
        ),
        migrations.AlterField(
            model_name='soledserial',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Sold', 'Sold')], default='Sold', max_length=400),
        ),
    ]
