# Generated by Django 3.2.13 on 2022-05-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buen', '0009_alter_soledserial_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soledserial',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Sold', 'Sold')], default='Sold', max_length=400),
        ),
    ]
