# Generated by Django 3.2.13 on 2022-05-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buen', '0011_alter_soledserial_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=15)),
                ('serial_number', models.CharField(max_length=200)),
                ('winner', models.BooleanField(default=True)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Sold', 'Sold')], default='Sold', max_length=400)),
                ('date_created', models.DateField(auto_now=True)),
                ('time_created', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='soledserial',
            name='winner',
            field=models.BooleanField(default=True),
        ),
    ]
