# Generated by Django 3.2.13 on 2022-05-27 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buen', '0012_auto_20220525_0437'),
    ]

    operations = [
        migrations.AddField(
            model_name='soledserial',
            name='validation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='soledserial',
            name='winner',
            field=models.BooleanField(default=False),
        ),
    ]
