# Generated by Django 3.2.13 on 2022-05-29 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buen', '0013_auto_20220527_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='soledserial',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buen.soledserial')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
